apiVersion: apps/v1
kind: Deployment
metadata:
  name: steve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steve
  template:
    metadata:
      labels:
        app: steve
    spec:
      containers:
        - name: debian
          image: debian:unstable
          command: ["/bin/sleep", "3650d"]
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
          env:
            #- name: MARIADB_RANDOM_ROOT_PASSWORD
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: "0" # if it is 1 and root_password is set, root_password takes precedance
            - name: MARIADB_ROOT_PASSWORD
              value: secret
